export enum Category {
  FICCAO = "FICCAO",
  NAO_FICCAO = "NAO_FICCAO",
  FICCAO_CIENTIFICA = "FICCAO_CIENTIFICA",
  FANTASIA = "FANTASIA",
  MISTERIO = "MISTERIO",
  ROMANCE = "ROMANCE",
  TERROR = "TERROR",
  BIOGRAFIA = "BIOGRAFIA",
  HISTORIA = "HISTORIA",
  INFANTIL = "INFANTIL"
}